### ISSUE TITLE
Chat color/emoji/nicknames

### ISSUE THREAD

**Issue by helloworld** [Schmavery/facebook-chat-api#124]
Messenger recently released an update to change a chat's color and default emoji.

Is there anyway to incorporate changing them into this API?

**Comment by blazeu** [comment]
Yes,
but currently the Facebook web doesn't have them (at least for me) so, i suggest we should wait until it's released on Facebook web.

**Comment by bsansouci** [comment]
Yes and messenger.com has it. We can definitely add it, but it'll take us a couple of days once we get free time. @Schmavery?

**Comment by helloworld** [comment]
That would be awesome! I can think of some very cool use cases already if this were to be implemented.

**Comment by Schmavery** [comment]
I want this functionality but realistically it might be a little while before we find the time to reverse engineer it.  Pull requests are welcome as usual <3

**Comment by qcmaude** [comment]
Although messenger.com shows the custom colours, nicknames and emoji, it does not allow you to update them. This is strictly an app feature for now. As @blazeu said, once it's implemented in the web UI, we'll add it :smile:

**Comment by helloworld** [comment]
When it is implemented, could I work with one of you to help implement it? I'd love to learn the process behind reverse engineering the requests!

**Comment by Schmavery** [comment]
@helloworld @qcmaude @webfreak7 Looks like it's finally time...

![image](https://cloud.githubusercontent.com/assets/2154522/13544050/22f78228-e226-11e5-9555-4cd6c56e3c0a.png)

**Comment by Schmavery** [comment]
We did some preliminary work on this last night.  Because the endpoints for these functions only seem to be available from messenger.com, it seems that we will have to add support for making requests to messenger.com as well as facebook.  This seems like the option that will give the most flexibility long-term so it is probably worth it.  For now, making duplicates of all facebook cookies has gotten us some progress, but we're still experiencing some errors so this will require additional investigation.

As a sidenote, we were able to replay the change color/emoji requests from firefox and break the web UI by setting the emoji to one that is unsupported.  You can also set the color of the chat to any html color code.  Fun.

![image](https://cloud.githubusercontent.com/assets/2154522/13613153/c6be35c2-e51f-11e5-8e64-b0c62c498e38.png)

**Comment by Schmavery** [comment]
Just so people know, we've given the api the ability to make calls to messenger.com now in order to enable changing the color/emoji.  Feel free to keep your eyes out for interesting endpoints only available on messenger.com

**Comment by ErmanSayin** [comment]
@Schmavery What about nicknames? 😎😎

**Comment by Schmavery** [comment]
@ErmanSayin feel free

**Comment by GAMELASTER** [comment]
@Schmavery 
I think we can close this because I did the last part of issue. :-)

**Comment by Schmavery** [comment]
Reading the information is just as important as writing it if you ask me.  Should be fixed by the introduction of getThreadInfo, which I should have time to finish up this weekend.

**Comment by Schmavery** [comment]
I just pushed getThreadInfo, which lets you check what these values are set at for a given thread.  Thanks to everyone, special shoutout to @GAMELASTER for his `changeNickname` function. :smile:
