### ISSUE TITLE
Could not find thread for a chat with 5 people

### ISSUE THREAD

**Issue by gmork** [Schmavery/facebook-chat-api#141]
As a followup of https://github.com/Schmavery/facebook-chat-api/issues/138, filing this issue as a feature request: group chats get selected based upon a conversation's name, which is a non-required property for Facebook. 

This returns as an error `{"error":"Could not find thread."}` for the affected group chat as a result for the api.listen callback.
  
I haven't had the time yet to find the circumstances in which this problem occurs (for me it occured in a unnamed group chat with 5 persons). Will try so asap.

**Comment by Schmavery** [comment]
Riiight okay I'm beginning to see what the problem could be.  We have a special code path that happens for group chats with more than 5 people because facebook doesn't give us all the users for group chats when they're too big.
I've always hated the use of searchForThread to solve this problem but thought we could get away with it.  Guess we'll have to revisit this when we get a chance.

**Comment by bsansouci** [comment]
Yeah, the problem comes from [this line](https://github.com/Schmavery/facebook-chat-api/blob/443aaac49aca426a4031affeb14d481cedc6af47/src/listen.js#L163-L164). I just pushed a fix, can you try?

**Comment by bsansouci** [comment]
This is a better fix ^

**Comment by gmork** [comment]
Thanks guys!
