### ISSUE TITLE
How does the login work?

### ISSUE THREAD

**Issue by nicolas-martin** [Schmavery/facebook-chat-api#160]
I want to apologize in advance, because this isn't an issue but more of a question.

I'm just curious as to how the login work, from what I understand. It first tries to scrap the `lsd` from the login page then tries to post to `https://www.facebook.com/login.php?login_attempt=1` and then grabbing the `fb_dtsg` token for later requests.

But for some reason when I try to replicate the login request, it doesn't work. I tried posting this json body 
```json
{"email":"email@email.com",
"pass":"password",
"locale":"en_US",
"non_com_login":"",
"lsd":"AVq0BqAV"}
```

Am I missing something here?

**Comment by Schmavery** [comment]
Hey @nicolas-martin,
You'll probably have the most luck working through the makeLogin function in index.js (@bsansouci feel free to correct me) , which is where we log in.  If you have any specific questions about the code in there, feel free to ask.
You might want to double-check that your cookies are right if you 're having trouble imitating the browser.

**Comment by bsansouci** [comment]
@Schmavery's right about cookies. My best guess is that you're not keeping track of all of them. We're using [saveCookies](https://github.com/Schmavery/facebook-chat-api/blob/d4ec3e8521370eb748e4369c70cbe3dd75507ee2/utils.js#L536) to save cookies on requests that return relevant ones. We also need to scrape the html to get the other ones, because FB uses JS to inject cookies. We do that [here](https://github.com/Schmavery/facebook-chat-api/blob/d4ec3e8521370eb748e4369c70cbe3dd75507ee2/index.js#L130-L144).
