### ISSUE TITLE
getUserInfo returning 404 to listen() in a chat with >4 people

### ISSUE THREAD

**Issue by ErmanSayin** [Schmavery/facebook-chat-api#178]
Hello, I get a 404 error on the console whenever there's a message sent to a group chat.
It still happens when there's nothing on the login callback function.
Same problem on the last stable version, and git version.

Here's the result of adding console.log(data) on utils:505:
http://pastebin.com/raw/3n9b4Bbp

**Comment by bsansouci** [comment]
Hey @ErmanSayin, I just tried on my side and sending a message works. Could you login, do something like `fs.writeFileSync("someAppState.json", JSON.stringify(api.getAppState()), 'utf8');` and send me the file at `benjamin.sansouci@gmail.com`. I should be able to login using that cookie on that account and test it out. If you feel like revoking access you can simply login and then call `api.logout` and it'll invalidate that cookie.

It's due to `/chat/user_info` being an invalid url for some reason. Can you try sending a message to a chat with multiple people?

**Comment by ErmanSayin** [comment]
@bsansouci Oh sorry, I meant when someone else in a group chat sends a message. It works fine on single-user conversation.

**Comment by bsansouci** [comment]
Ah well that doesn't change much haha. In either case the problem seems to be in getUserInfo (whether it's called from listen or from sendMessage).

**Comment by ErmanSayin** [comment]
I kinda got around the issue by hardcoding the group ID in the code so `listen` doesn't use `getUserInfo` when there's a message

**Comment by bsansouci** [comment]
The cookies stopped working for me. I think they get invalidated as soon as you re-login with the same account. If you want me to explore a little more on my side you can send me the actual credentials so I can login and try things. I find this issue very weird because I don't understand how an endpoint like `/chat/user_info` can return `404` for you and not for me.

**Comment by Schmavery** [comment]
After doing some looking into this issue, it looks like the culprit is the hack to retrieve the list of participants from the html of the page [here](https://github.com/Schmavery/facebook-chat-api/blob/master/src/listen.js#L164-L201).

I would recommend making a change to make a call to the `thread_info.php` (the same endpoint as called by getThreadHistory).  This seems to return the full list of participants under `payload.threads[0].participants` when called as follows with the threadID and the current userID.
```
threads[thread_fbids][0]:<ThreadID>
messages[thread_fbids][<ThreadID>][offset]:0
messages[thread_fbids][<ThreadID>][timestamp]:
messages[thread_fbids][<ThreadID>][limit]:10
```

**Comment by Schmavery** [comment]
@ErmanSayin @asdfasdfvful can someone sync to master and verify that this commit fixes the issue?

**Comment by asdfasdfvful** [comment]
@Schmavery all I need to do is npm install facebook-chat-api again correct? I did that and I'm still getting the same error

**Comment by asdfasdfvful** [comment]
I deleted the node_module files and reinstalled it just to make sure. Here is the log in case something changed

http://pastebin.com/Pi3bd5yB

**Comment by ErmanSayin** [comment]
@Schmavery listen works for me, although `sendMessage` is broken, no errors

**Comment by ErmanSayin** [comment]
@asdfasdfvful remove `facebook-chat-api` from `node_modules`, then do `git clone https://github.com/Schmavery/facebook-chat-api.git`, then do `npm update` inside the new `facebook-chat-api` folder

**Comment by asdfasdfvful** [comment]
Thanks a lot to all of you! It's fixed

**Comment by Schmavery** [comment]
Thanks for the confirmation guys.  I'll push to npm tonight.
