### ISSUE TITLE
Event is self-listen by default

### ISSUE THREAD

**Issue by blazeu** [Schmavery/facebook-chat-api#21]

**Comment by bsansouci** [comment]
Hey! Not totally sure what you mean by this. Can you give us more information about your problem? The default is false in the code and seemed to work when we tried it just now.

**Comment by blazeu** [comment]
By event, i mean when type is "event", like when changing the title and adding or removing participant

**Comment by bsansouci** [comment]
Ok should be fixed by 89c10f72d25007b53a9d042234973fe87a8764bb

**Comment by blazeu** [comment]
it seems like this fix isn't published in the npm packages.

**Comment by Schmavery** [comment]
I just published to npm so that should show up shortly.
Next time if you want changes that we haven't published yet, you can always modify your package.json to pull directly from the github repo.  Just use `git://github.com/schmavery/facebook-chat-api` as the version.  We sometimes like to get confirmation that a change works before publishing it.

**Comment by blazeu** [comment]
thanks!
