### ISSUE TITLE
getThreadHistory starting time seems to be ending time

### ISSUE THREAD

**Issue by scottopell** [Schmavery/facebook-chat-api#238]
I have a call that looks like this:
`api.getThreadHistory(build_cool_shit, 0, 10000, lastTime, function(err, history){ ... do stuff ... }`

and I have a chat that looks like this:
```
[ { msg: 'hello', timestamp: 1459867565000,
  { msg: 'testing', timestamp: 1459867566000,
  { msg: 'world', timestamp: 1459867789000 } ]
```
and what I'm seeing is that if I set `lastTime` to `1459867566000`, I get the chats *previous* to and including `testing`. I would expect to get `world` and any messages after it.

Am I using this api wrong or has anybody seen this behavior before?

**Comment by Schmavery** [comment]
@bsansouci @EvanStoddard23 #230 Maybe our docs have it backwards?

**Comment by Schmavery** [comment]
@UsmannK can you confirm that this is backwards?

**Comment by UsmannK** [comment]
Yes, the docs have it backwards.

Instead of :
`timestamp`: Used to described the start time. If set, will query messages from `timestamp` to `Date.now()`

It should be something along the lines of:
`timestamp`: Used to described the end time. If set, will query messages with timestamps up to and excluding `timestamp`
