### ISSUE TITLE
Handle Security Check

### ISSUE THREAD

**Issue by wklm** [Schmavery/facebook-chat-api#255]
Hey,

While pasting a link I'm getting the Security Check "Please select all the photos which show a tiger." How can I handle that?

**Comment by avikj** [comment]
This happens to me to. I think it's how facebook attempts to block bots/spammers. You probably have to change the bot's messaging pattern, because there isn't a good way around it. For me, it happened because I was sending file names which would be recognized as URL's by the spam detection. To get around that I just replaced the '.' in the file name with a ','.

**Comment by bsansouci** [comment]
We can't go around that. The best thing I can recommend is just using the newly announced official API: https://developers.facebook.com/docs/messenger-platform/implementation.
