### ISSUE TITLE
Color & Emoji Setting Not Working

### ISSUE THREAD

**Issue by mjkaufer** [Schmavery/facebook-chat-api#257]
I've been trying to set the color and emoji to no avail. [The bot](http://github.com/mjkaufer/AutoColor) I had previously created is no longer working. I'm guessing FB changed some settings or the color endpoints, or maybe is now verifying that the colors/emojis being set are part of the predefined FB emoji set...

**Comment by Schmavery** [comment]
Are you saying that they all don't work?  We're not planning to do verification of the emoji/colour in the api, so if some don't work, I think we're ready to consider that a user error for now...

**Comment by GAMELASTER** [comment]
For me its all working, if you want list of all emojis, look here:
https://www.piliapp.com/facebook-symbols/

**Comment by bsansouci** [comment]
Closing since it seems to be working on our @GAMELASTER's end.
Emojis are very problematic because of their inconsistencies between platforms. I'd recommend against using them for the purpose of a customer facing bot. You can find a lot of articles on the internet about the differences in emotions conveyed by the same emoji depending on the platform. That's for the ones that do work on all platforms, but there's a whole set of emojis that just plain don't work or cause weird glitches to happen.
