### ISSUE TITLE
Cannot Login "You're temporarily restricted from creating open graph actions until Tomorrow"

### ISSUE THREAD

**Issue by ilhamiarie** [Schmavery/facebook-chat-api#273]
Today , I encountered an error during login .

error log "Couldn't login. Facebook might have blocked this account. Please login with a browser or enable the option 'forceLogin' and try again."

I try to login via the browser , display a notification like this :

"You're temporarily restricted from creating open graph actions until Tomorrow at 1:31am"

can anyone experienced this?

**Comment by ahmedaloui** [comment]
I had the same problem.

**Comment by bsansouci** [comment]
Is this still happening or was it a fluke?

**Comment by ahmedaloui** [comment]
it happens when we send messages to a facebook contact from facebot. facebook consider it as an unsecure action. 
"Facebook has implemented regulations to reduce risk behaviors that could be considered annoying or abusive."

**Comment by bsansouci** [comment]
This sounds like FB thinks you're doing something sketchy. Have you been sending lots of messages to random people that aren't your friends? If so we can't do anything about this.

**Comment by mbennette68** [comment]
I just encountered the same issue today.  Haven't really sent anything to anyone I don't know.  Just posted on groups I'm a member of and shared with friends.

**Comment by bsansouci** [comment]
My guess is those are FB's imperfect spam heuristics at play :/
Then again, if they're aiming at blocking bots then... they're doing a good job at it lol

**Comment by mbennette68** [comment]
I has to be cause all I've done is use spark.adobe.com, to share video presentations.  It appears to be the only way that the adobe watermark can go away. There re posts that come from the groups that I've subscribe to and they do come frequently.  I've disabled those. Then there is also this [Facebook status page](http://downdetector.com/status/facebook) I don't see anything about Graph issues but some people reporting that what they share is not showing up.

Thanks,
MB

**Comment by TWINKEEXII** [comment]
This happened to me yesterday.

**Comment by Schmavery** [comment]
I'm having a hard time understanding exactly what is happening here.  Can someone explain more clearly what is going on?

**Comment by mbennette68** [comment]
Could be that the malware that Facebook is looking for might actually be Illegal Software.  Facebook would not let me login 'til I downloaded and scanned my system with FSecure.exe.  I let it do it, it scanned my system, then found nothing.  Don't know if what they are doing is legal or not, but really frustrating having to endure that waste of time.

**Comment by Schmavery** [comment]
@mbennette68 Do you think you could open a new issue summarizing your experiences here? Since no other comments mention FSecure.exe, I'm wondering if this is a new problem.  Either way, this is a pretty sucky experience for people using the API.  Still hard to tell if this is behavioural or due to the api calls, so details in exactly what you are doing with the api are helpful.
I guess there's a small possibility they're detecting that calls are being made with expired cookies and flagging that.

**Comment by mbennette68** [comment]
Well, I don't know what the issue is, but I, said, I suspect that F-Secure's real scanning target is not Malicious Browser Extensions, but rather Illegal Software Installs.  All I was doing was testing out Adobe Spark ( spark.adobe.com ) which creates video presentations with music, graphics and effects all for free + a watermark which can be downloaded without a watermark after the entire video is shared to your timeline or wherever with the watermark.  As soon as I tried to share the presentation video, I got hit with the problem.  

As mentioned before, I tried to do it from two browsers, in my Windows 10 machine, and also in my IPad. Both outcomes were identical. Also note that I also had issues posting to the Group I am a member of.  I don't think posting in that group had anything to do with it.  The funny think is that it got worse as I was not even able to post a Youtube link, or any links for that matter.

I tried to deal with that issue for two days, finally took pictures of the errors, sent a request to 
Facebook to have them fix the issue, and also emailed helsinki@f-secure.com ( the only email I know as I don't have Zuckerberg's email ) to complain, but I doubt that either Facebook or F-Secure will pay much attention to me.  

I find it pointless to start a new issue as nothing will get solved.  I had to go through the process though it took me three days, more or less, I finally was able to get back into Facebook, after they scanned my system and acquire whatever info, they were looking for.  Of that I have no doubt.  

If the issue was occurring on a large scale throughout the net, then I'd say, yeah, it's Facebook trying to limit bots, or stuff like that.  As this is happening selectively, then I'm more inclined to think that the reasoning behind this is something else.

If however, you wish to know what I did, the steps I took, here's a [ image](https://ibin.co/2o5933HirhTU.png) of my email to 
FSecure.

**Comment by HeNeArKrXe** [comment]
Seems to be Facebook pushing everyone under their umbrella programming. Either to go after bots and fake news (like trying to kill a spider by burning a part of the house down), or to try pushing their pretty-much-useless malware scanner onto everyone again. 

The Facebook forums have a lot of people complaining about getting this ban, but no one from Facebook has stepped in to tell anyone why it's happening, why so many people are being affected; or to even explain to its general users what "graph actions" are to begin with, as most users are casual ones, with no reason to be familiar with that term until this happens to them. 

If everyone reported it as a problem, instead of going straight to the forums, though, Facebook may actually do something about it. Multiple reports of problems don't look good to shareholders, and shareholder money talks louder than forum users ever could.
