### ISSUE TITLE
GetOnlineUsers broken

### ISSUE THREAD

**Issue by tomexsans** [Schmavery/facebook-chat-api#278]
```
info Logging in...
info Logged in
info Request to reconnect
info Request to pull 1
info Request to pull 2
info Request to thread_sync
info Done logging in.
ERR! Error in getOnlineUsers Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.

ERR! Error in getOnlineUsers     at C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\utils.js:538:42

ERR! Error in getOnlineUsers     at tryCatcher (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)

ERR! Error in getOnlineUsers     at Function.Promise.attempt.Promise.try (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\method.js:31:24)

ERR! Error in getOnlineUsers     at C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\utils.js:523:24

ERR! Error in getOnlineUsers     at tryCatcher (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)

ERR! Error in getOnlineUsers     at Promise._settlePromiseFromHandler (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\promise.js:507:31)

ERR! Error in getOnlineUsers     at Promise._settlePromiseAt (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\promise.js:581:18)

ERR! Error in getOnlineUsers     at Promise._settlePromises (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\promise.js:697:14)
ERR! Error in getOnlineUsers     at Async._drainQueue (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\async.js:123:16)

ERR! Error in getOnlineUsers     at Async._drainQueues (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\async.js:133:10)

ERR! Error in getOnlineUsers     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\tomex\Desktop\check\node_modules\facebook-chat-api\node_modules\bluebird\js\main\async.js:15:14)

ERR! Error in getOnlineUsers     at processImmediate [as _immediateCallback] (timers.js:383:17)

ERR! Error in getOnlineUsers  [Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.]

[Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.]
```

**Comment by Schmavery** [comment]
Looks like facebook changed something on their end.

**Comment by j6k4m8** [comment]
Bummer. This was exactly what I was looking for! @Schmavery I'm happy to contribute a fix, do you have any thoughts on where to get started before I just start poking around?

**Comment by Schmavery** [comment]
Yeah sorry about this.  Haven't had a lot of time to look into it lately.  If you could contribute a fix, that would be awesome.
If I'm not mistaken, the original function used the same data as the right-hand sidebar in facebook.com, which, at the time, it got from "https://www.facebook.com/ajax/chat/buddy_list.php".  If I'm wrong, @bsansouci can correct me.  It looks like facebook has since changed their way of sending this information to the client, so the fix would consist of finding the new way that the information is sent and updating src/getOnlineUsers to retrieve the information in that way instead.  Feel free to update this issue with any progress even if you can't figure it out fully and I'd be happy to help in any way I can.

**Comment by j6k4m8** [comment]
Hehehehe alright here we go...

So I thought that it might be smart to try to reverse-engineer the data coming down the line from the React UI in Facebook (and Messenger), both of which use (as far as I can tell) the same `pull/` endpoint. 

So I opened up dev tools, went to network, and waited a few seconds for a `pull/?content...` request to come through.

Finally got one: It started with:

```
for(;;); {t":"msg","seq":87,"u":678######,"ms":[{"type":"chatproxy-presence","buddyList":{"100006611######":{"lat":1464######},"720######":{"lat":1464######,"p":0,
...
```

...alright. That's definitely data. The `for`, as far as I can tell, just makes the file valid JS instead of JSON. Not sure what that's for, though education is always welcome if there's a GitHubber in the audience who knows. Anyhow, it's definitely not useful data to us, so let's delete it and start with the big JSON object.

Anyhow, I decided to search for a user ID that I recognized. I opened up React DevTools in Chrome, inspected the top chat element in the Buddy List, and got `userID: 153...7`.

Seems like a safe bet that somewhere in my enormous `pull/` JSON, there's a user ID, right? And if that's my first "buddy", then I'll bet it's included in this list, even if the list is truncated. Let's [prettify](https://jsonformatter.curiousconcept.com/) the remaining JSON and take a look at the structure.

AHA. If you search for `153...7`, you get a structure like this:

```json
"153...7":{
    "lat":1464727775,
    "p":2,
    "vc":10
},
```

Lat? I thought Facebook stopped storing location data for chats... (Eh. They probably still record it. Whatever.)

So what's lat? Try:

```js
> new Date(1464727775)
"Sat Jan 17 1970 17:52:07 GMT-0500  (EST)"
```

Okay, that's wrong... But wait — shouldn't a datestamp in millis have more digits than that?

```js
> new Date(1464727775 * 1000)
"Tue May 31 2016 16:49:35 GMT-0400 (EDT)"
```

That looks more reasonable. `lat` = "Last Active Time", is my guess.

-----

This lines up with Facebook's recent switch from greenlight/greylight → meaningful status indicators about 'last seen' times (e.g. `1m` for "one minute ago"). It's possible that we can't find these data because they no longer exist..?

Btw, the other variables, `p` and `vc`, are not necessarily present for every buddy on the list: Some only have `lat`, so I looked there first. It's possible one of the other attributes indicates 'here'ness.

**Comment by Schmavery** [comment]
Wow, that's some good sleuthing!

I'm pretty sure what you're doing right now is reinventing our preexisting "presence" notification api.  If you search for "presence" in our api docs, you should be able to find it.  It does push-based notification when we get presence information about another user.  
What getOnlineUsers did was provide a one-time call (pull-style) that will return all information about online users.  If Facebook has changed their frontend to remove this endpoint, we will simply have to deprecate the API function, unfortunately.
Note: There are a couple different reasons for the for(;;), some of which are explained nicely by [this post](http://stackoverflow.com/questions/6339790/what-does-a-ajax-call-response-like-for-json-data-mean).

**Comment by j6k4m8** [comment]
Ah — I thought presence was per-user (this returns a *loooong* dictionary of userID → status). I'll do some more searching! 

How would you feel about a retrofit that satisfies the same API but pings the backend a few times to get the equivalent info as the old endpoint?

PS: thanks for the `for` reference!

**Comment by Schmavery** [comment]
Hmm, yeah it might be different, @bsansouci thoughts?
Generally we've been trying to avoid hacks that do too many backend calls magically.  A bigger problem I can see here is that doesn't seem to really be a way to request this information, so we'd have to process these /pull messages and cache them in the api to be able to give the same experience as the old endpoint, maybe?  If there was a way to trigger the sending of the long dictionary of users, I'd consider it, but as a /pull, that seems unlikely...

**Comment by bsansouci** [comment]
I don't think waiting for a `/pull` is a good idea. Caching data is beyond the scope of this API I'd say because there most likely will be a bunch of edge cases that will depend on the use case. I'd rather keep this layer of abstraction thin and have people build on top. @j6k4m8 you could most definitely build your own caching that'll keep track of who's logged in when.
The best solution would be to find a real endpoint that we can hit that returns that information.

**Comment by j6k4m8** [comment]
That's absolutely what I thought as well, @bsansouci. Just wanted to update on what I found before making any executive decisions :)

I'll keep you updated on what else I find! I'll keep playing around this week.

**Comment by tomexsans** [comment]
I think they are checking the **last active time** or **last active timestamp** 
thinking maybe 5minutes to 10 minutes is good for online then sends the data to

https://www.facebook.com/chat/user_info/?dpr=1

which in turns display the profile with name on the sidebar.

thats why when a user is online and we click on it it turns offline.
