### ISSUE TITLE
Its possible use proxy for logins?

### ISSUE THREAD

**Issue by fccoelho7** [Schmavery/facebook-chat-api#291]
I'm beeing blocked when I send my app to dropplet.

**Comment by bsansouci** [comment]
I'm not sure what you mean by proxy in this case. If you mean it literally, I don't think this API can do much. You'll probably want your whole network connection to go through some other server.

**Comment by fccoelho7** [comment]
I thought in something like that: http://codingmiles.com/node-js-making-https-request-via-proxy/

**Comment by GAMELASTER** [comment]
I think is enough to add to the REQUEST defaults the link to proxy, REQUEST module can handle it.

**Comment by fccoelho7** [comment]
Yes, @GAMELASTER. I've success but Facebook continues blocking account. I think Facebook doesn't accept connection from a distance place of common place connections.

**Comment by bsansouci** [comment]
@fccoelho7 Can't you make FB accept the place you connect from as being trustworthy? We had problems with our bot at the beginning but as long as we consistently connected from the same place, it was fine. Maybe you can make your droplet stay in the same location.

**Comment by fccoelho7** [comment]
Yes.. That's the project: http://aubott.com/

**Comment by Schmavery** [comment]
@bsansouci I think he can't do it that way because he wants users to be able to sign up and have his service Just Work™ without blocking their account with random logins from strange locations.  It's my opinion that our API is not designed to support this scenario and never really was.  You're going to be getting and storing user Facebook passwords and that just seems.. bad.

Anyway, the only way to get around this issue would probably be the proxy.  @fccoelho7, did @GAMELASTER's suggestion work for enabling the proxy?  If there is a simple code change for this, we would consider a PR.  Otherwise there is not much we can do about this.

**Comment by Schmavery** [comment]
Going to close this due to the reasons in my previous comment.  Please feel free to followup with developments about using a proxy!  We're always interested :smile:
