### ISSUE TITLE
Getting rid of node

### ISSUE THREAD

**Issue by Dudelmoser** [Schmavery/facebook-chat-api#298]
Hey guys, 

as far as I can see, this package "simply" emulates the requests of the messenger/facebook web client. So shouldn't it be possible to get rid of the node.js dependency in order to allow writing a custom messenger client which has no need for a dedicated server or a local node installation?

Thanks in advance

**Comment by bsansouci** [comment]
This issue has been addressed on multiple occasions: #103 and #290 

The problem remains the same: you can't have this client-side only because of cross origin requests (from your own domain name to FB's). The browser won't allow this.
Feel free to make a chrome extension, all you need is to replace the stdout/strerr streams (look at the issues attached).
Feel free to fork this and make a branch that is detached from nodejs. Also feel free to reimplement this in other languages, we love to see stuff like [fbchat](https://github.com/carpedm20/fbchat) happen and we wish people pursued it more. 
Closing this to keep our issues clean, but feel free to continue the discussion here.

**Comment by Dudelmoser** [comment]
Thank you for linking those two threads - they show that it should be possible quite effortless. I guess I'll be using Apache Cordova. I can white list domains for cross site scripting there.

**Comment by Schmavery** [comment]
Awesome, be sure to link us to anything you manage to get working :smile:
