### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by jijoamt** [Schmavery/facebook-chat-api#30]
I have updated the library and was able to get messages yesterday. But today am not able to login. it says "Wrong username/password" . seems headers.location is missing. Can you pls check the issue

**Comment by bsansouci** [comment]
We changed the `login` function, check the docs. Did you update your code accordingly?

**Comment by JLarky** [comment]
I see same issue, I resolved it by adding noscript cookie

``` javascript
    function loginReq(res, email, password, jar) {
      jar.setCookie("noscript=1", "https://www.facebook.com");
```
index.js line 20

**Comment by jijoamt** [comment]
Yup, That fixed the  issue. Thx @JLarky

**Comment by bsansouci** [comment]
@JLarky mmh thanks, we'll look into that. Probably gonna add it if it fixes it :+1:

**Comment by JLarky** [comment]
I think main idea is that now in browser I see more options that are getting added to form from js, so you either have to emulate that or (as I guessed) you can try logging in as non-js user. I just afraid that later option can be removed by facebook later, since facebook doesnt work without js anyways.
