### ISSUE TITLE
Not running this API on AWS server

### ISSUE THREAD

**Issue by ppyoosuf** [Schmavery/facebook-chat-api#309]
Hi

This API is running on localhost. but , when i hosted on AWS server this producing wrong username or password error

please help me

**Local host**

node 5.4
npm 6.8

**AWS**

node 6.2
npm 6.9

thanks

**Comment by lulalachen** [comment]
Did you set `USERNAME` and `PASSWORD` as environment variables on AWS?

**Comment by KeNt178** [comment]
I've got the same type of error. When I'm running the node server normally everything works fine, when I've browserified my app I've got the "Wrong username/password." error.
I thinks it is not the actual reason since we both know our creds :)

**Comment by Schmavery** [comment]
How are you passing in the username/password?
Maybe you might have some success writing res.body to disk [here](https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L155) and opening the html in a browser.  It's obviously pretty hard for us to repro this on our side so the debugging will be tough without help.

**Comment by ppyoosuf** [comment]
hi guys

but i have replaced the same code with other facebook account user name and
password then it works on localhost and the aws.in old account i have used
the username as mobile number.is any problem for mobile number using as
email fields?

**Comment by Schmavery** [comment]
This api hasn't been tested using mobile numbers to log in, but feel free to give it a try.

**Comment by ppyoosuf** [comment]
why the mobile number is works on localhost?

**Comment by KeNt178** [comment]
Hi guys,

At first sight, _headers_ variable doesn't contain the _location_ field. I tried to manually set it to _https://www.facebook.com/_ which is the default value I have when I don't browserify my app.
I now have the _Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify._ error.

It may be caused by permissions we should add in conf files of chrome extension or AWS ?

**Comment by Schmavery** [comment]
@KeNt178 I'm assuming you tried to log in with this account using the browser to verify it hasn't been blocked?  You could also try printing out the contents of the `html` variable to a file and opening it in a browser to see what facebook is trying to tell you at that moment.

**Comment by KeNt178** [comment]
@Schmavery Yes of course ! The exact same code works when not browserified, and no longer works when browserified, weird...
I will try that thanks

**Comment by KeNt178** [comment]
@Schmavery When I print the html variable and open it in my browser, I get the home page of my facebook account (expected behaviour). The bug is in the recorvery of the cookies : [maybeCookie](https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L38) is empty because [jar](https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L37) is empty too.

**Comment by Schmavery** [comment]
Right, I guess the problem might be with when we get the cookies in the first place.  I'm not sure where we get c_user specifically (maybe [here](https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L146)?)  @bsansouci might remember better than me.
If you get the homepage of your facebook account, that's actually a good sign, it shows that we're successfully signing in, we're just failing on retreiving your userID from the cookies.

**Comment by bobland1** [comment]
I run from AWS it runs fine. Make sure you havnt installed any unwanted software within Linux

**Comment by bobland1** [comment]
Install the bleading edge version, and run npm install, npm update. Make sure you have laid it out as 

- [ ] 1. Folder

- [ ] 2. bot.js and node_modules folder within ^^

- [ ] 3. Run Node bot.js
Note as soon as you close putty or ctrl c. It will stop the process, Consider installing forever.

**Comment by bobland1** [comment]
_Once installed forever (optional) type forever start -m5 bot.js

To stop, run forever stop bot.js_
