### ISSUE TITLE
message.participant_ids only returns 5 people

### ISSUE THREAD

**Issue by canzhiye** [Schmavery/facebook-chat-api#31]
It seems that message.participant_ids only returns 5 people.

**Comment by bsansouci** [comment]
You mean it returns 5 people max? How many people are there in your chat?

**Comment by blazeu** [comment]
Confirmed.

There are 70 people in my chat, and ```participant_ids``` & ```participant_names``` only returns 5 ids & names

**Comment by bsansouci** [comment]
Mmmh I just tried it, you're right. It's because the UI won't show you more, you have to specifically ask for the participants if you do want more. There's the number though `participant_total_count` which we can add as part of the packet. If it's bigger than 5 we can have a hook to pull their data.
