### ISSUE TITLE
Is there any technique to get these form data ?

### ISSUE THREAD

**Issue by Larry850806** [Schmavery/facebook-chat-api#342]
Hello @Schmavery. I'm trying to make a api that can do some post. I try to login in using "request" module like you. But it's too difficult. I see part of your code:

```js
var form = utils.arrToForm(arr);
form.lsd = utils.getFrom(html, "[\"LSD\",[],{\"token\":\"", "\"}");
form.lgndim = new Buffer("{\"w\":1440,\"h\":900,\"aw\":1440,\"ah\":834,\"c\":24}").toString('base64');
form.email = email;
form.pass = password;
form.default_persistent = '0';
form.lgnrnd = utils.getFrom(html, "name=\"lgnrnd\" value=\"", "\"");
form.locale = 'en_US';
form.timezone = '240';
form.lgnjs = ~~(Date.now() / 1000);
```

I try to observe the http request and get some data like `form.lgndim`. But I can't find where to get `form.lgnjs = ~~(Date.now() / 1000)`. Is there any technique to analyze that what happen when I click login?

**Comment by bsansouci** [comment]
Hey @Larry850806, thanks for spending the time to do this, this is generally a lot of tedious work... 

I'm not 100% sure what your question is. Are you asking how we figured out that `lgnjs` was a timestamp? If so, the answer is we totally guessed by taking the number we saw from the request, multiplying by 1000 and checking whether that was a valid date (and close to now). 
If you're asking where we found that field because you can't find it when you make your own request, then either the FB API changed or you're missing one request. When you login there's a page change, and by default the browsers will clear all the stuff in the network tab when you change pages (in chrome). If you want to see everything without losing any requests you have to tick this 
<img width="727" alt="screen shot 2016-10-12 at 11 49 16" src="https://cloud.githubusercontent.com/assets/4534692/19323458/e1b9d3a6-9071-11e6-9ccb-1c7ee9a5f4e4.png">
The `preserve logs` box next to `disable cache`.

If you're asking more generally how the heck we figured this out, then here's how we did it:
- do some action with the network tab open
- list ALL the fields from the form (and query parameters)
- go through each and ... guess: base64 encoded? timestamp? token generated clientside (there's a looot of those for some reason)? hardcoded string (yes there are tons of those too)? etc..
- the hardest ones are the token generated clientside because they require you to look at the minified JS code. We downloaded the whole HTML page + all the scripts (just `cmd+s` on the page in chrome lol) and then started `grep`-ing for stuff like `lgnrnd`. As you explore the code, don't hesitate to [beautify the js](http://jsbeautifier.org/) and save it. Sometimes those tokens are just embedded in the HTML which makes our utils function `utils.getFrom` very useful (give it a string, start token and end token and it gives you everything in between). It's hacky but it's been working for over a year now :)

I hope this answers at least some questions if not the one you were asking.

**Comment by bsansouci** [comment]
@Larry850806 Oh also check out [the graph API](https://developers.facebook.com/docs/graph-api/using-graph-api). It might simplify your life a lot.

**Comment by Larry850806** [comment]
@bsansouci I get the data that I want after I tried the tips you said. As you said, there is a lot of tedious and hard work. Thank you very much. Your answer does solve my problem.

**Comment by Schmavery** [comment]
Haha I believe it!  Thanks for getting back to us about your success :)
