### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by checkium** [Schmavery/facebook-chat-api#368]
The bot is able to send and read messages, and I have listenEvents enabled, but the bot ins't listening for events, only messages.

**Comment by bearbear12345** [comment]
Can you show us your code?

**Comment by checkium** [comment]
Currently my PC os broken, and Im trying to fix it, I will show you The code when its fixed (maybe not soon)

**Comment by Schmavery** [comment]
@bearbear12345 I'm assuming it's working for you still?

**Comment by mvojtrip** [comment]
it doest work for me too here is my code

var login = require("facebook-chat-api");

login({email: "***", password: "***"}, function callback (err, api) {

if(err) return console.error(err);
  api.setOptions({listenEvents: true});

    var stopListening = api.listen(function(err, event) {
        if(err) return console.error(err);

        switch(event.type) {
          case "message":
    






            break;
          case "event":
api.addUserToGroup("******", "*****", function callback(err) {
        if(err) return console.error(err);
    });

api.addUserToGroup("*******", "*****", function callback(err) {
        if(err) return console.error(err);
    });
          






            break;
        }
    });
   

});

**Comment by bearbear12345** [comment]
Okay, it stopped working for me too now. Strange why it was still working for me for abit longer..

Looks like the events are now part of 'delta'

```
{ ofd_ts: ...,
  delta:
   { addedParticipants: [ [Object] ],
     irisSeqId: '...',
     messageMetadata:
      { actorFbId: '...',
        adminText: 'You added ....',
        messageId: '...',
        offlineThreadingId: '...',
        skipBumpThread: false,
        tags: [Object],
        threadKey: [Object],
        timestamp: '1484401782232' },
     class: 'ParticipantsAddedToGroupThread' },
  type: 'delta',
  iseq: ...,
  queue: ... }
```

**Comment by bearbear12345** [comment]
You'd have to check for ParticipantLeftGroupThread, etc in the delta case switch, and call another set of functions instead then..

Changes to utils.js```formatEvent()``` you'd need to reflect
```
threadID: v.delta.messageMetadata.threadKey.threadFbId,
logMessageType: v.delta.class,
logMessageData: {}, // Delete this line?
logMessageBody: v.delta.messageMetadata.adminText,
author: v.delta.messageMetadata.actorFbId
```

**Comment by bearbear12345** [comment]
Fixed in PR #369

**Comment by mvojtrip** [comment]
I tested the last version and it gives me this error :  (i didn't npm install facebook-chat-api (because it install the old version with the bug ) i did git clone and the install the requirimentns: bluebird,cheerio,npmlog,request)




ERR! ERROR in listen -->  ReferenceError: formattedEvent is not defined
ERR! ERROR in listen -->      at parsePackets (/root/node_modules/facebook-chat-api/src/listen.js:171:60)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /root/node_modules/facebook-chat-api/src/listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
ERR! ERROR in listen -->      at Async._drainQueue (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (/root/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! ERROR in listen -->   [ReferenceError: formattedEvent is not defined]
[ReferenceError: formattedEvent is not defined]

**Comment by Schmavery** [comment]
Thanks for letting us know, this was introduced by #369 @bearbear12345

**Comment by bearbear12345** [comment]
Oh whoops, I thought ```utils.formatEvent...``` was only used once.
Yep that looks right then

@Schmavery

**Comment by Schmavery** [comment]
I pushed an attempted fix, @mvojtrip can you try again?  Sorry about that.

**Comment by mvojtrip** [comment]
ok,now it works fine :)

**Comment by Schmavery** [comment]
Thanks for following up, :)
