### ISSUE TITLE
api.getThreadHistory doesn't work on group chats

### ISSUE THREAD

**Issue by tarungog** [Schmavery/facebook-chat-api#372]
Internally this function calls on the getUserInfo which I am assuming does not work on group chats. Could this be remedied by simply using the getThreadInfo function instead? All I know is that when calling this function on a group chat, it either freezes up or simply does not even execute the callback. No idea why that may be. Help would be appreciated
`        api.getThreadHistory(group, count - 5, count - 4, function callback(err, history) {
            if (err) console.error(err);
            console.log("control flow is coming here");
            console.log(history);
        });   `

This is the code I'm using. the messages do not print to the console, nor do any "err".

**Comment by bsansouci** [comment]
This one got me worried! You forgot the 4th parameter to the function [timestamp](https://github.com/Schmavery/facebook-chat-api/blob/9da530343e2510388bc8cb481f1074d67c463df1/DOCS.md#getThreadHistory). It wasn't doing anything because we accept [the callback optionally](https://github.com/Schmavery/facebook-chat-api/blob/9da530343e2510388bc8cb481f1074d67c463df1/src/getThreadHistory.js#L8) which is probably a poor decision. Sorry for the confusing. If you pass `Date.now()` you'll get what you're expecting.
