### ISSUE TITLE
How to accept message from strangers, these messages stay in Message Requests

### ISSUE THREAD

**Issue by codetay** [Schmavery/facebook-chat-api#377]
Hi, 

I just wonder about the method: api.handleMessageRequest and how to use it to handle messages in Message Requests

I tried:

```
api.listen(function callback(err, message) {
        //accept message for stranger
        api.handleMessageRequest(message.threadID, true);
});
```

but it didn't work !

**Comment by Schmavery** [comment]
Do we receive events for message requests in listen?  I wasn't aware of it, but maybe I'm wrong, the events are not particularly well understood.  Maybe you can check the other fields of the message object?

I would have suggested the use of [getThreadList](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apigetthreadliststart-end-type-callback).  If this still doesn't work, it's totally possible that handleMessageRequest has broken.  Can anyone else confirm that they're also seeing this problem?

Because of the nature of how this api works, things like this break from time to time and we always offer heartfelt thanks to our users for finding and helping fix them 😄

**Comment by Schmavery** [comment]
Hey @codetay, any luck using getThreadList to solve this?  I'm going to close this for now but please comment/reopen if this doesn't solve your problem.
