### ISSUE TITLE
HTTP API documentation?

### ISSUE THREAD

**Issue by IamCarbonMan** [Schmavery/facebook-chat-api#379]
In the interest of others who may want to implement this API for other languages or who want to implement low-level access, it would be useful to have  low-level documentation. From the README:

> This means doing the exact same GET/POST requests and tricking Facebook into thinking we're accessing the website normally.

Do all API methods correspond to a specific GET/POST request?

**Comment by Schmavery** [comment]
The api methods use a number of different requests that all change slightly over time as facebook updates their servers.  This is the main challenge in running an api like this.
I would be happy to consider accepting a set of docs that attempted to explain the HTTP API.  Unfortunately, it is not 100% understood (at least by me) and is definitely not designed to be easy to use directly.  There are a number of parameters that are simply passed blindly because the browser does so, and even one or two that are generated using code copied directly from the facebook client code.  I would also be concerned about keeping it in sync with the code.  We already have a hard enough time keeping the docs in sync (and that's not even talking about the time it takes to get the code to work when facebook updates).
I'd be curious to hear people's ideas on solutions to these problems.  Obviously it's always nice to have more things (features, documentation), but I'm just concerned as to the sustainability.

**Comment by IamCarbonMan** [comment]
I personally found this project while looking for a Messenger-to-IRC gateway, which would certainly be possible with the current API.

> There are a number of parameters that are simply passed blindly because the browser does so, and even one or two that are generated using code copied directly from the facebook client code.

Yeah, that's what I was afraid of- specifically the copying code part. The entire benefit of a documented HTTP API is that every language and platform speaks HTTP- but if we have to include JS code from Facebook then it's far less useful.

**Comment by Schmavery** [comment]
Don't get me wrong, nothing's preventing someone from reimplementing those bits in other languages (and afaik other people have), we just don't know how to explain why they exist.  The HTTP docs would be like "take an array of strings that looks like this and jumble them up according to this hash and pass them to the request".

**Comment by IamCarbonMan** [comment]
Right... I'd be happy to write docs for what you have now, but I'd much
rather write docs about things I understand. Do you think it's likely that
we'll ever figure out what all of this foreign code do?

**Comment by Schmavery** [comment]
It's possible!  We know a lot more now than we did before this repo existed 😆 

I'm still a little concerned about the feasibility of keeping such a document up to date.  Do you have any idea of how to manage this?  It's hard enough keeping the api itself working, and I frequently have to remind contributors to update the docs (or give up and do it myself).  I wonder if an inaccurate document can sometimes be worse than no document.

**Comment by IamCarbonMan** [comment]
I would first of all suggest using an actual documentation system like
JSDoc. You may even be able to set up pull request checks using Travis that
ensure everything is well documented (I'm not extremely familiar with
Travis, but I believe this would be fairly simple to set up).

You could probably also have one contributor in charge of just docs.

**Comment by Schmavery** [comment]
You could be right that we might benefit from a tool like JSDoc.  We had been trying to avoid needing any sort of build step, but it's true that we could conceivably set it up with travis or similar.

The trick is usually finding a contributor that matches that description and is willing to stick around long enough ;P  We always accept PRs with doc fixes.

**Comment by IamCarbonMan** [comment]
I'm happy to put some time into working on docs, although it might take some time to fully familiarize myself with the project.

**Comment by Schmavery** [comment]
Please feel free to let us know if we can help in any way :)

**Comment by IamCarbonMan** [comment]
Will do, thanks!
