### ISSUE TITLE
Callbacks should be returned so that api methods can be chained

### ISSUE THREAD

**Issue by enhdless** [Schmavery/facebook-chat-api#408]
It would be helpful for the `defaultFuncs` call in some api methods to be returned, so that api calls can be chained.

For example, currently the following code would get errors:
```
api.getUserInfo(id, (err, arr) => {
    return arr;
}).then(function(data) {
    console.log(data);
});
```

If instead [line 43 of getUserInfo.js](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getUserInfo.js#L43) is `return defaultFuncs`, the `then` in the above code would successfully run.

I can make a quick PR for this. 👍

**Comment by bsansouci** [comment]
Hey @enhdless, how often do you chain more than 2-3 api calls like this? 
We don't really see promises as simple, and we're a bit scared of exposing them to the user. Errors/exceptions get hairy with promises (arguably promises are a problem in the codebase right now because we don't handle errors correctly).

Callbacks are simpler to understand :)

**Comment by ivkos** [comment]
@enhdless If you need promises, you can use bluebird's [`Promise.promisify(api.someFunc)`](http://bluebirdjs.com/docs/api/promise.promisify.html). I'm using it in my project and it works fine, except for `api.listen(cb)` which isn't suitable for promises because it invokes `cb(err, msg)` everytime it receives a message. 

E.g.:
```js
Promise.promisify(api.getUserInfo)(id)
   .then(info => { ... })
   .catch(err => { ... })
```

**Comment by Schmavery** [comment]
Thanks @ivkos, I was thinking there much be something like this.
@enhdless would this work for you?

**Comment by enhdless** [comment]
Ah I wasn't aware of promisify, seems like it'll suit my needs perfectly. Thanks @ivkos!
