### ISSUE TITLE
Create changelog

### ISSUE THREAD

**Issue by AllanWang** [Schmavery/facebook-chat-api#480]
I think it would be worthwhile to continue creating releases on the github repo (latest is 1.2.0) and add either a Changelog.md or changelog in the releases so users can see what has changed. Features are added all the time, and some of them may break bot code for older versions, and it would be nice to have an easier way to distinguish which portions need to be changed without sifting through the commits.

**Comment by ravkr** [comment]
Great idea! I was thinking about it few weeks ago... :/
And I think that we should also put some clues how to update code (what someone have to change to get the same result as before)

**Comment by Schmavery** [comment]
@AllanWang I suppose we could start this, if someone wants to take a quick look at the past couple versions and see what has changed.  I've held off up to this point because it's yet another barrier to people trying to submit PRs (on top of keeping docs up to date).
I generally try to make up for this by trying my best not to create breaking changes.  Can you give some examples of problems you ran into lately?

**Comment by AllanWang** [comment]
@Schmavery I still haven't updated my bot yet but I know we were talking about threadHistory having arguments that don't work, leading to [this](https://github.com/Schmavery/facebook-chat-api/commit/ad25b6b60a252c1b8c3f39780cfe369bde7bb495) PR.

If you're okay with it, I can create a Changelog.md and maintain it at least for the summer (and likely during the school year as well). If Github releases are created again I can link to the specific changes/new features so it will be easier for others to update.

**Comment by Schmavery** [comment]
@AllanWang yeah that's a good example of the type of change that comes along now and then where the old version doesn't work anymore because of a change on facebook's end, which forces us to change the signature.

If you want to start a simple Changelog.md that covers the last couple releases that would be great, and I'll try to encourage people to add to the top of it whenever we make any breaking changes.  I'll have to see if I can make some time to go back and add the github release tags where I missed them

**Comment by AllanWang** [comment]
@Schmavery could you make a release tag now just so I can link things to a specific commit when I make the log? Otherwise I'll link it to the latest commit upon creation rather than to a release

**Comment by Schmavery** [comment]
@AllanWang Just tagged a couple, let me know if I missed something.

**Comment by ravkr** [comment]
@Schmavery this should be closed now
