### ISSUE TITLE
 Error in getUserID TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by rafaelangarita** [Schmavery/facebook-chat-api#491]
Is getUserID not working?

It was working flawlessly for me until today.

```
info Logged in 
info Request to reconnect 
info Request to pull 1 
info Request to pull 2 
info Request to thread_sync 
info Done logging in. 
ERR! Error in getUserID TypeError: Cannot read property 'type' of undefined
ERR! Error in getUserID     at facebook-chat-api/src/getUserID.js:44:19
```

**Comment by Ptomerty** [comment]
Seconding this; not sure if FB's API is down, but getUserInfo works just fine.

**Comment by Schmavery** [comment]
getUserInfo uses a completely different endpoint, so that's probably not related.
A number of calls have been failing lately because it looks like facebook is gradually switching over to a graphql-based query system, especially for searches.  We don't have a full answer to this yet, as always, we welcome exploration and suggestions.

**Comment by Ptomerty** [comment]
Seems to be up now, close please.

**Comment by bsansouci** [comment]
@rafaelangarita Closing for now. Feel free to reopen if this still happens to you.
