### ISSUE TITLE
Error in sending message

### ISSUE THREAD

**Issue by Yeonin** [Schmavery/facebook-chat-api#500]
I saw this issue on solved ones but I tries using the latest commit, the commit on the solved thread and other solutions but none worked.

```
ERR! getUserInfo { __ar: 1,
ERR! getUserInfo   __sf: 'j0',
ERR! getUserInfo   error: 1357004,
ERR! getUserInfo   errorSummary: 'Sorry, something went wrong',
ERR! getUserInfo   errorDescription: 'Please try closing and re-opening your browser window.',
ERR! getUserInfo   payload: null,
ERR! getUserInfo   bootloadable: {},
ERR! getUserInfo   ixData: {},
ERR! getUserInfo   lid: '6443046541094488234' }
```

**Comment by bsansouci** [comment]
Hey @Yeonin, thanks for reporting this. Are you able to send any messages or do you immediately get this error?
Could you try with a different account to see?
Could you log into the account you're using and check that it doesn't ask you to verify anything? We've observed weird responses when running bots on machines that are in totally different places than where the account usual logins from, because FB thinks it's someone who took control of your account.

One last thing that would help: is there any way you could give us access to the account that's having that issue? We can't reproduce it with our accounts, it's likely that this only happens in your region. If you can't share the bot's account with us, maybe try making a new account and reproducing the issue with that one and sharing that one with us?

Also this might be due to sending repeated messages to a bunch of people or non-friends. (that's why trying with a different account helps).

**Comment by Yeonin** [comment]
There's an error immidiately after trying to send. And I receive a message
that my account was logged in from a different device. I was able to
receive message details like body and threadid but isnt able to send
anything. I am using the same PC that I regularly use for facebook.

**Comment by Schmavery** [comment]
@Yeonin it would help to have more details.  Can we see some code that produces this issue? Can you include the contents of the error you just mentioned?  Have you tried logging into this specific account in the browser?  If you're able to go through @bsansouci 's steps one by one and let us know the results, that would be really helpful.

**Comment by TerriACaS** [comment]
I have the same error when sending a message

**Comment by Schmavery** [comment]
This is one of the most generic errors and unfortunately without more information, it is basically impossible to diagnose.  Feel free to reopen when applicable.
