### ISSUE TITLE
No more messages after 2300 message

### ISSUE THREAD

**Issue by ImJustToNy** [Schmavery/facebook-chat-api#504]
Hello!
First, I want to say huge "thanks" to all contributors of this project. It makes manipulating facebook chat very easy.
Second, I'm asking you for help. What I was trying to do is get all messages from my over-5-years-old facebook chat group. To do that, I've created simple function which is getting all messages from newest to oldest (every loop, timestamp variable is overwritten with new value) and inserting them into database. But I found a little problem. After exactly 2300 messages, second parameter from callback of function getThreadHistory returns a empty array, (which is strange beacuse I'm 100% sure that after all of this years, we wrote more messages than 2300) and first argument (err) is also empty. I'm not sure what to do over there. Do you have any experience in terms of fixing stuff like that?
Thanks!

**Comment by ivkos** [comment]
Are you requesting the message history from an account that has been a member of the chat group since it was created, or one that joined it later? 

I've hit a similar problem with a bot account that I added later to a group and it couldn't see the oldest messages - only a few thousand back. The workaround was to get all messages using my personal account that is a member since the beginning.

**Comment by gamelaster** [comment]
I noticed last time that I can't access really old messages and images.
Thank you Facebook for loss many of images... :rage:

**Comment by ImJustToNy** [comment]
Thanks!
