### ISSUE TITLE
How To Get Messages From My FB Page

### ISSUE THREAD

**Issue by riftshock** [Schmavery/facebook-chat-api#517]
so basically I this will enable me to recieve/send messages from my account.
but is there a way that I could read all messages from my Fb Page and not just directly from my main Fb account? 

`login(credentials, {pageID}, (err, api) => {

      api.listen((err, message) => {

        console.log(message);

    });

});`

I also tried it like this:

`login(credentials,(err, api) => {

      api.setOptions({pageID: pageID});

      api.listen((err, message) => {

        console.log(message);

    });

});`

Cool Package by the way. Helped me a lot. Keep it up guys 👍

**Comment by riftshock** [comment]
so I kind of figured it out what i was lacking was setting listenEvents to true:

` api.setOptions({
        pageID: pageID,
       listenEvents: true
      });`

but my now the problem is it doesn't return any body from the sender

this is the return object

`{ isTyping: false,

  from: '<from-id>',

  threadID: '<thread-Id>',

  fromMobile: true,

  userID: '<user-id>',

  type: 'typ' }`

**Comment by riftshock** [comment]
well I guess the problem is related to #468

**Comment by Schmavery** [comment]
Thanks for the troubleshooting, sorry it's not working yet (also sorry it took me long to respond).
I think that the fix has been identified and probably isn't too crazy, if you wanted to give it a shot. I've been really busy but I'd be super happy to help you with that in any way.

Just to keep issues organized, I'm going to close this one so that we can keep everyone in #468 up to date.  Thanks for reporting!
