### ISSUE TITLE
User gets locked. Forcelogin does not work

### ISSUE THREAD

**Issue by xuezhma** [Schmavery/facebook-chat-api#518]
When our server logs a user in. His account will be locked. I played with forcelogin trying confirm the login from our server. In the end, I managed to reach to a page that tells me `To continue, please approve this login on a phone or computer you've used before.` 

Any work around to avoid user being locked? Or confirm his login without requiring any action from the user's side? Thanks

**Comment by Schmavery** [comment]
This is an unofficial api that doesn't make any attempts to work around safety measures instituted by facebook to prevent abuse of their system.  In practice, we've found that making bots that have roughly the same usage patterns as people (don't spam messages, don't log in repeatedly from many places) don't have troubles getting blocked.

**Comment by bsansouci** [comment]
Another thing to think about is location, if the server's in a totally different place than the user, FB will ask the user if everything's alright. 
I'll echo @Schmavery, we don't encourage bypassing security measures. Forcelogin is merely a script automatically clicking on "yes it was me at this location" because that was often a question FB asked.
