### ISSUE TITLE
Mismatched types pageID

### ISSUE THREAD

**Issue by Atachi** [Schmavery/facebook-chat-api#59]
When using the current dev branch, login in as page is broken due to the given ID internally turned into a string.
After editing the setOptions function, to not convert pageID into a string, receiving messages as page works.
This breaks preventing selfListen though as there it is expected to be a string in the comparison.

In short: somewhere along the line there is a type mismatch, that prevents pageID to be properly compared.

**Comment by Schmavery** [comment]
Hmm, because Facebook gives us ids as strings, we're currently working with the general rule that all ids should be stored at strings to avoid too many problems on this type.  I'll take a look when I get a chance.  Do you know where it broke the first time, before you changed `setOptions`?

**Comment by Schmavery** [comment]
Hey @Atachi, can you let me know if this fixes your problem? :smile:

**Comment by Atachi** [comment]
Hi.

I was talking about the "pre-release-v1.0" branch. In "master", pages were working.
Currently have to use that branch due to requiring the external stopListening feature still missing in the master.

Sorry if that hasn't been clear in the original message.

**Comment by Schmavery** [comment]
Awesome, thanks.  Coincidentally, there was exactly the same problem in the master branch.  Just heading to work now but hopefully it'll be fixed by the end of the day.  Feel free to try and submit a pull request if you want to give it a shot!  It's not too hard, lots of guides online and I don't mind helping out!

Note: if you do make a pr, can make sure we convert the passed in page id to a string in `setOptions`?  (That's in index.js)
