### ISSUE TITLE
When will there be a new package on NPM ?

### ISSUE THREAD

**Issue by codeforequity-at** [Schmavery/facebook-chat-api#619]
I want to include the progress in my projects Testmybot and Botium, but the package on npmjs.org is rather old. I also don't want to point directly to the Git repository.
When will there be a new package released ?

**Comment by ravkr** [comment]
@Schmavery will probably release new version after merging #572, #612, #617 and maybe #603
But this is just my guess

**Comment by Schmavery** [comment]
That's the plan. @bsansouci and I worked on the weekend to try and get everything merged & unified a bit so that we can push a working version out to npm. We ran out of time in the end but hope to finish up tonight. Sorry for the delay, it can be hard to make time for this and there's quite a few fiddly details involved in making the datatypes line up and deciding how the format we expose should evolve as fb changes what they expose.

**Comment by ALiangLiang** [comment]
Maybe you can use "pre-release" to keep latest version? Also if someday FB api is changed, you can release many unstable hotfix version to prevent disaster.

**Comment by Schmavery** [comment]
Hey @ravkr, @ALiangLiang , we did our best to merge in the GraphQL versions of getThreadInfo and getThreadHistory in the dev branch tonight. If you have a chance, feel free to give them a try and see if there are any bugs we missed before we merge to master and publish to npm.

**Comment by ravkr** [comment]
@Schmavery I noticed that the new code contains `...Url` in the returned objects but I think that we should call it `...URL` (as we do with `ID` and not `Id`)

**Comment by Schmavery** [comment]
@ravkr I went with Url because that's how we've written it in the past.. hard to know with some of these things haha

As an update, we merged the dev bench to master and planning to publish soon.

**Comment by ravkr** [comment]
@Schmavery I thought that if we are changing so much to unify style, this could also be changed to match the style (and because `URL` is normally typed uppercase)

---

I don't think that prettier was a good choice
These new if statements and throws splitted to multiple lines are not looking good in my opinion :(
![obraz](https://user-images.githubusercontent.com/3875202/37698363-d753d646-2ce2-11e8-99ce-101105edaff8.png)
![obraz](https://user-images.githubusercontent.com/3875202/37698381-ef64630e-2ce2-11e8-880b-2080056d6dd0.png)

same here, why use 5 lines instead of just one? :/ Now I can display less code at once on my screen
![obraz](https://user-images.githubusercontent.com/3875202/37698437-46282aa4-2ce3-11e8-8b58-6398fdf9e900.png)

**Comment by bsansouci** [comment]
@ravkr we don't want to spend time arguing about coding style here, there is so much other work to do. Thanks for expressing your opinion but we'll move forward with using Prettier and its default rules.

**Comment by Schmavery** [comment]
We published version 1.5.0 to npm today. Thanks for everyone's patience.
