### ISSUE TITLE
'canReply' field referenced but doesn't exist in the documentation.

### ISSUE THREAD

**Issue by 23phy** [Schmavery/facebook-chat-api#696]
Oy everyone,
In the table [here](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apigetthreadinfothreadid-callback), at the key named `cannotReplyReason`, `canReply` is referenced but I cannot see it. So where should this `canReply` key exist?

**Comment by Schmavery** [comment]
I just looked at the code for this, and it looks like we deprecated the canReply field because it's redundant with cannotReplyReason but never updated the docs. Thanks for pointing it out. https://github.com/Schmavery/facebook-chat-api/blob/61ddf3ce02767ac5c04f93232567cc7e67fb1afe/src/getThreadInfo.js#L115

Tried to improve it just now: https://github.com/Schmavery/facebook-chat-api/commit/1a0adcfeff340dd038a0b4cfb238716d5e6e62fd
