### ISSUE TITLE
Messenger.com no longer sends API requests to messenger.com/api/graphqlbatch/

### ISSUE THREAD

**Issue by abdou4a** [Schmavery/facebook-chat-api#860]
As I sometimes write my own Bots by just opening chrome devtools (network tab) to copy the request (as node-fetch) and use it in my code... that means without using this facebook-chat-api 
Yesterday, I tired to scroll up the chat thread to capture the api request that retrieves the chat history, chrome devtools didn't show anything!... so I came across this repo to find that it makes requests to messenger.com/api/graphqlbatch/
My question is:
How did you come with this info? (which api endpoint and witch request params to send)

**Comment by BadAimWeeb** [comment]
In the past, Facebook is communicating using REST API, GraphQL and AJAX, and every request can be seen on the DevTools. But, Facebook recently updated, they are using a MQTT connection over WebSocket to communicate now, that's why you don't see anything.

**Comment by RealTrisT** [comment]
you can still check it in devtools by filtering the network requests by "WS" (websockets) and then clicking the messages tab. They do have a heartbeat now every like second or so, a bunch of garbage is sent everytime you send or receive a message too. Maybe someone working on this project might know what most of it is. I was starting to think of REint it, but their whole thing is a mess and there's probably gonna be a boatload of bugfixes and all that since it's recent. Some guy in a newer issue said he got locked out of his acct, so if that's true they're probably cracking down on anyone trying to use the API outside their garbage little webapp.

**Comment by Schmavery** [comment]
Yeah, the API has gone through a lot of changes over the years with gradual rollout making it hard to track exactly. The migration to the new systems have been slow and incremental so frequently the old APIs still work for quite a while even if the current browser frontend doesn't use them. There have been some attempts to rewrite this library with functions like "listenMqtt", but it's hard for anyone to have enough stamina to finish a complete rewrite and any attempt to do this would end up breaking compatibility anyway, so it would likely require a major version update (and who knows how long that will last).

Unfortunately this approach to writing an API is fairly doomed for anything that needs stability and we're at the mercy of fb's decision to not create a public API.

**Comment by BadAimWeeb** [comment]
> Maybe someone working on this project might know what most of it is. I was starting to think of REint it, but their whole thing is a mess and there's probably gonna be a boatload of bugfixes and all that since it's recent.

yes.
I'm rewriting this library (in OOP style) and being overwhelmed with a ton of new things, 90% of this codebase need to be rewritten.

~~my brain are lagging~~

**Comment by Schmavery** [comment]
haha I don't know that switching paradigms will solve the problems but I wish you luck!
