### ISSUE TITLE
Logging in makes account locked

### ISSUE THREAD

**Issue by hoangvu12** [Schmavery/facebook-chat-api#864]
Every time I log in to my Facebook account, Facebook just locked out my account for some reason. I've tried changing user agent etc but still checkpoint. Does anyone have the same problem?

**Comment by abdou4a** [comment]
This probably due to change in IP address 
I remember (maybe a year ago) I was locked out because I hosted my bot on Glitch 
But when I run my bot locally it works fine!
So, I generated appstate.json locally and uploaded it to Glitch... so my bot will use the same session without logging from Glitch again

**Comment by hoangvu12** [comment]
> This probably due to change in IP address 
> I remember (maybe a year ago) I was locked out because I hosted my bot on Glitch 
> But when I run my bot locally it works fine!
> So, I generated appstate.json locally and uploaded it to Glitch... so my bot will use the same session without logging in from Glitch again

I got this problem when running locally, so It's not IP problem...

**Comment by Schmavery** [comment]
#852
