### ISSUE TITLE
How to get typing indicator?

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#92]
There is method **api.sendTypingIndicator()** to send the typing indicator. But there doesn't seem to be anyway to receive an indicator? 

My first feeling was that it should be part of "**listen()**" function with event listening enabled. But so far I haven't seen any such event.

Regards.

**Comment by bsansouci** [comment]
Good catch! If you do `api.setOptions({listenEvents: true})` you should get typing indicators now :)

**Comment by nripendra** [comment]
Is it published to npm? Or I should get directly from github?

**Comment by Schmavery** [comment]
I just published the updates to npm.  In general, getting it directly from github will get you the latest code, because we don't publish after every commit (unless it's something really important).
You should be able to listen for 'typ' events. @bsansouci correct me if I'm wrong, but that's what the code looks like.

**Comment by Schmavery** [comment]
@bensansouci reopening this so that we remember to update the docs.

**Comment by bsansouci** [comment]
Yes `type; 'typ'`, and yeah we need to document this properly.

**Comment by Schmavery** [comment]
Fixed docs in d3cd027.
