### ISSUE TITLE
addUserToGroup incorrect thrown error

### ISSUE THREAD

**Issue by pete10** [Schmavery/facebook-chat-api#98]
Hi,

Just started using this api and really impressed, thanks for all the hard work so far!

I have noticed a problem with addUserToGroup feature though, I am able to successfully add a user to a group chat using the api despite an error being thrown...

ERR! ERROR in addUserToGroup -->  { __ar: 1,
ERR! ERROR in addUserToGroup -->    error: 1545052,
ERR! ERROR in addUserToGroup -->    errorSummary: 'Unable to add user.',
ERR! ERROR in addUserToGroup -->    errorDescription: 'The user could not be added to the conversation. Please try again later.',
ERR! ERROR in addUserToGroup -->    payload: null,
ERR! ERROR in addUserToGroup -->    jsmods: { require: [ [Object] ] },
ERR! ERROR in addUserToGroup -->    bootloadable: {},
ERR! ERROR in addUserToGroup -->    ixData: {},
ERR! ERROR in addUserToGroup -->    lid: '6215920767082530033' }

Are you able to look into this?

Thanks

Peter

**Comment by Schmavery** [comment]
Thanks for opening an issue about this.
We actually noticed it yesterday and it seems to be something funny on Facebook's side (since it still adds the user to the chat and you will get an event saying a user was added to the chat).  It's possible that they've changed the format of the request, so we'll keep an eye on it, but for now I guess I would say you should just ignore this error.

**Comment by pete10** [comment]
Okay no problems at all! Thanks for looking into that!

Peter

**Comment by Schmavery** [comment]
Definitely, thanks for bringing it to our attention :)
